name: inventario_domestico
description: Una aplicación para gestionar el inventario doméstico.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  intl: 0.19.0
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  image: ^3.2.2
  
  # Nuevas dependencias para funcionalidades de ajustes
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  permission_handler: ^10.2.0
  file_picker: ^5.2.5
  csv: ^5.0.1
  share_plus: ^6.3.0
  excel: ^2.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true