name: inventario_domestico
description: Una aplicación para gestionar el inventario doméstico.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.11
  win32: ^5.0.0  # Actualiza a la última versión estable
  
  # Nuevas dependencias para funcionalidades de ajustes
  permission_handler: ^11.4.0  # Esta versión ya la tienes
  file_selector: ^1.0.3  # Ya tienes esta versión
  http: ^1.3.0  # Ya tienes esta versión
  image: ^4.3.0  # Ya tienes esta versión
  image_picker: ^1.1.2  # Ya tienes esta versión
  intl: 0.19.0  # Ya tienes esta versión
  share_plus: ^10.1.4  # Ya tienes esta versión
  csv: ^6.0.0  # Ya tienes esta versión
  excel: ^4.0.6  # Ya tienes esta versión
  timezone: ^0.10.0  # Ya tienes esta versión
  provider: ^6.0.5  # Usa la última versión estable
  shared_preferences: ^2.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true